export const vendorCodes = [
  { code: 'CA', name: 'MasterCard' },
  { code: 'VI', name: 'Visa' },
  { code: 'AX', name: 'American Express' },
  { code: 'DC', name: 'Diners Club' },
  { code: 'AU', name: 'Carte Aurore' },
  { code: 'CG', name: 'Cofinoga' },
  { code: 'DS', name: 'Discover' },
  { code: 'GK', name: 'Lufthansa GK Card' },
  { code: 'JC', name: 'Japanese Credit Bureau' },
  { code: 'TC', name: 'Torch Club' },
  { code: 'TP', name: 'Universal Air Travel Card' },
  { code: 'BC', name: 'Bank Card' },
  { code: 'DL', name: 'Delta' },
  { code: 'MA', name: 'Maestro' },
  { code: 'UP', name: 'China UnionPay' },
  { code: 'VE', name: 'Visa Electron' },
];
